[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ani-sync"
version = "2.11.13"
authors = [
  { name="Idris Haris", email="idrisharis@users.noreply.github.com" },
]
description = "Stream anime in terminal with 64x turbo speed & automatic MyAnimeList tracking"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Topic :: Multimedia :: Video",
]
dependencies = [
    "requests>=2.25.0",
    "tqdm>=4.60.0",
    "Pillow>=9.0.0",
]
keywords = [
    "anime",
    "terminal",
    "watch-anime-in-terminal",
    "cli-anime-player",
    "terminal-anime-streaming",
    "myanimelist-sync",
    "anilist-sync",
    "kitsu-sync",
    "mpv",
    "fzf",
    "syncplay",
    "aniskip",
    "termux",
    "linux-anime",
]

[project.scripts]
ani-sync = "ani_sync:main"

[project.urls]
"Homepage" = "https://github.com/idrisharis12/ani-sync"
"Bug Tracker" = "https://github.com/idrisharis12/ani-sync/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["ani_sync*"]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312', 'py313']

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
